# Generated by Django 5.2.6 on 2025-10-14 18:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(choices=[('GAS', 'Gasolina/Transporte'), ('SAL', 'Salário/Ajuda de Custo'), ('COM', 'Compras/Suprimentos'), ('ADM', 'Administrativo'), ('OUT', 'Outros')], max_length=3)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa da ONG',
                'verbose_name_plural': 'Despesas da ONG',
                'permissions': [('view_financeiro', 'Pode visualizar o módulo financeiro')],
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('PI', 'Pausa Início'), ('PF', 'Pausa Fim'), ('S', 'Saída')], max_length=2)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('localizacao_gps', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização (GPS)')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-timestamp'],
            },
        ),
    ]
