# Generated by Django 5.2.6 on 2025-10-14 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco_bairro', models.CharField(max_length=100, verbose_name='Endereço/Bairro')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('frequenta_nova_igreja', models.BooleanField(default=False, verbose_name='Frequenta a Nova Igreja')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviços',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Atendimento')),
                ('queixa', models.TextField(verbose_name='Queixa/Motivo do Atendimento')),
                ('observacoes_outras', models.TextField(blank=True, null=True, verbose_name='OUTROS (Comentários do Formulário)')),
                ('profissional_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profissional Responsável')),
                ('pessoa_atendida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.pessoa', verbose_name='Pessoa Atendida')),
                ('servico_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_principais', to='atendimento.tiposervico', verbose_name='Serviço Principal')),
                ('servicos_utilizados', models.ManyToManyField(related_name='atendimentos_utilizados', to='atendimento.tiposervico', verbose_name='Equipes/Serviços Utilizados (Múltipla Seleção)')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
    ]
